import "@/assets/css/styles.scss";
import { Footer, Header } from '@/components';
import { StoreProvider } from "@/stores/store-provider";

require('dotenv').config()
import NextTopLoader from 'nextjs-toploader';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader />

        <StoreProvider>
          <Header />
          <main>
            <div className="container">
              {children}
            </div>
          </main>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  )
}
