import "@/assets/css/styles.scss";
require('dotenv').config()
import { Footer, Header } from '@/components';

import { StoreProvider } from "@/stores/store-provider";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        <StoreProvider>
          <Header />
          <main>
            <div className="container">
              {children}
            </div>
          </main>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  )
}
